name: Azure Web App Deployment


inputs:
  app_name:
    required: true
  credentials:
    required: true
  token:
    required: true
  resource_group:
    required: true
  artifact_workflow:
    required: true
  artifact_name:
    required: true
  package_type:
    required: false
    default: .zip
    description: Default value is .zip
  storage_account:
    required: true
  container:
    required: true
  subscription:
    required: true



env:
  EXPIRY: 10 minutes

runs:

    using: 'composite'
    steps:
    - name: Azure login
      uses: azure/login@v1
      with: 
        creds: ${{ inputs.credentials }}

    - name: Downlaod artifact
      uses: Legit-Labs/action-download-artifact@v2
      with:
        name: ${{ inputs.artifact_name }}
        workflow: ${{ inputs.artifact_workflow }}
        github_token: ${{ inputs.token }}
        path: ${{ github.workspace }}

    - name: Set SAS token expiration
      run: echo "expiry=`date -u -d "$EXPIRY" '+%Y-%m-%dT%H:%MZ'`" >> $GITHUB_ENV
      shell: bash

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.19.1
        inlineScript: |
          az storage blob upload --account-name ${{ inputs.storage_account }} -c ${{ inputs.container }} -f app.zip --type block --name myblob
          APP_URL=$(az storage blob generate-sas --full-uri --permissions r --expiry ${{env.EXPIRY}} --account-name ${{ inputs.storage_account }} -c ${{ inputs.container }} -n "myblob" | xargs)
          az rest --method PUT \
                  --uri https://management.azure.com/subscriptions/${{ inputs.subscription }}/resourceGroups/${{ inputs.resource_group }}/providers/Microsoft.Web/sites/${{ inputs.app_name }}/extensions/onedeploy?api-version=2020-12-01 \
                  --body '{ 
                      "properties": { 
                          "properties": {
                              "packageUri": "'"${APP_URL}"'"
                          }, 
                          "type": "zip"
                      }
                  }'
