version: '3.7'
services:

    app:
        build: .
        command: npm run start:prod
        ports:
            - "3025:3025"
            - "5858:5858"
        cap_drop:
            - ALL
        cap_add:
            - CHOWN
