name: Azure Web App Deployment

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 'Call deploy action'
      uses: thalissonOrg/azureDeploy@main
      with:
        app_name: 'python-test-thali'
        resource_group: ${{ secrets.RESOURCE_GROUP }}
        credentials: ${{ secrets.CREDENTIALS }}
        artifact_name: app
        artifact_workflow: .github/workflows/build.yml
        token: ${{ secrets.TOKEN }}
        storage_account: 'storage_account'
        container: 'storage_container'
        subscription: 030c7dc2-36f4-4344-b31d-fae06c275516
