name: Azure Web App Deployment

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 'Call deploy action'
      uses: thalissonOrg/azureDeploy@main
      with:
        app-name: 'python-test-thali'
        resource-group-name: ${{ secrets.RESOURCE_GROUP }}
        credentials: ${{ secrets.CREDENTIALS }}
        artifact_name: app
        artifact_workflow: Azure Web App Configuration
        token: ${{ secrets.TOKEN }}
