name: Azure Web App Email

on:
  workflow_dispatch:
    inputs:
      moduleName:
        description: 'Module Name'
        required: true
      moduleStack:
        description: 'Module Stack'
        required: true
      environment:
        description: 'Environment'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          

      - name: execute py script # run main.py
        env:
          TO_EMAIL: thalisson1980@gmail.com 
          MESSAGE: "${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} was a ${{ job.status }}, see more details on https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks/${{ github.run_id }}"
          SMTP_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python mailSender.py
     
