name: Azure Web App Deployment

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v1
      with: 
        creds: ${{ secrets.CREDENTIALS }}

   

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'python-test-thali'
        resource-group-name: '${{ secrets.RESOURCE_GROUP }}' 

