name: Azure Web App Configuration

on:
  workflow_dispatch:
    inputs:
      moduleName:
        description: 'Module Name'
        required: true
      moduleStack:
        description: 'Module Stack'
        required: true
      environment:
        description: 'Environment'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set inputs as environment variables
        run: |
          echo "MODULE_NAME=${{ github.event.inputs.moduleName }}" >> $GITHUB_ENV
          echo "MODULE_STACK=${{ github.event.inputs.moduleStack }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
        shell: bash

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r service.${MODULE_NAME}/requirements.txt

      - name: Azure login
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.CREDENTIALS }}


      - name: Send email
        if: always()
        uses: thalissonOrg/azureDeploy@main
        with: 
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: thalisson1980@gmail.com 
          message: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} was a ${{ job.status }}, see more details on https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks/${{ github.run_id }}